name: NetFx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore SMS2FA.sln

    - name: Set up local configuration
      run: copy "SMS2FA.Web\Local.config.example" "SMS2FA.Web\Local.config"

    - name: Build Web App
      run: msbuild SMS2FA.sln /verbosity:minimal

    - name: Run Tests with NUnit Console
      run: .\packages\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console SMS2FA.Web.Tests\bin\Debug\SMS2FA.Web.Tests.dll
